remove dependency which is needed
but not finding the right version at LNGS

ERROR: Could not find a version that satisfies the requirement boto3sts (from cygno) (from versions: none)
ERROR: No matching distribution found for boto3sts